/*
===========================================================
Topic       : Random SQL Practice Questions
Database    : MyDatabase
Description : A collection of miscellaneous SQL practice
              questions solved while learning SQL.
              This file will be updated with new questions
              and solutions over time.
Author      : Suryansh 
===========================================================
*/

USE MyDatabase;

-----------------------------------------------------------
-- Q1. Calculate the total number of orders placed
-- in each month.
-----------------------------------------------------------
SELECT
    FORMAT(OrderDate, 'MMM yy') AS Order_Month,
    COUNT(*) AS Total_Orders
FROM Sales.Orders
GROUP BY FORMAT(OrderDate, 'MMM yy')
ORDER BY MIN(OrderDate);

-----------------------------------------------------------
-- Q2. Find customers whose score is higher than
-- the average customer score.
-----------------------------------------------------------
SELECT
    ID,
    First_Name,
    Score
FROM Customers
WHERE Score >
(
    SELECT AVG(Score)
    FROM Customers
)
ORDER BY Score DESC;

-----------------------------------------------------------
-- Q3. Find the customer with the highest score.
-----------------------------------------------------------
SELECT
    ID,
    First_Name,
    Country,
    Score
FROM Customers
WHERE Score =
(
    SELECT MAX(Score)
    FROM Customers
);

-----------------------------------------------------------
-- Q4. Find customers who have never placed an order.
-----------------------------------------------------------
SELECT
    ID,
    First_Name,
    Country,
    Score
FROM Customers
WHERE ID NOT IN
(
    SELECT Customer_ID
    FROM Orders
);

-----------------------------------------------------------
-- Q5. Find the highest total sales generated by a customer.
-----------------------------------------------------------
SELECT
    MAX(TotalSales) AS Highest_Total_Sales
FROM
(
    SELECT
        Customer_ID,
        SUM(Sales) AS TotalSales
    FROM Orders
    GROUP BY Customer_ID
) AS SalesTable;

-----------------------------------------------------------
-- Q6. Find the highest single order value
-- for each customer.
-----------------------------------------------------------
SELECT
    ID,
    First_Name,
    MAX(Sales) AS Highest_Sales
FROM Customers
LEFT JOIN Orders
    ON Customer_ID = ID
GROUP BY
    ID,
    First_Name
HAVING MAX(Sales) IS NOT NULL
ORDER BY Highest_Sales DESC;

-----------------------------------------------------------
-- Concepts Covered
-----------------------------------------------------------
-- ✓ GROUP BY
-- ✓ ORDER BY
-- ✓ Aggregate Functions
-- ✓ COUNT()
-- ✓ MAX()
-- ✓ SUM()
-- ✓ Subqueries
-- ✓ Nested Queries
-- ✓ Joins
-- ✓ LEFT JOIN
-- ✓ HAVING
-- ✓ NOT IN
-- ✓ FORMAT()