/*
===========================================================
Topic       : Random SQL Practice Questions
Database    : MyDatabase
Description : A collection of miscellaneous SQL practice
              questions solved while learning SQL.
              This file will be updated with new questions
              and solutions over time.
Author      : Suryansh 
===========================================================
*/

USE MyDatabase;

-----------------------------------------------------------
-- Q1. Calculate the total number of orders placed
-- in each month.
-----------------------------------------------------------
SELECT
    FORMAT(OrderDate, 'MMM yy') AS Order_Month,
    COUNT(*) AS Total_Orders
FROM Sales.Orders
GROUP BY FORMAT(OrderDate, 'MMM yy')
ORDER BY MIN(OrderDate);

-----------------------------------------------------------
-- Q2. Find customers whose score is higher than
-- the average customer score.
-----------------------------------------------------------
SELECT
    ID,
    First_Name,
    Score
FROM Customers
WHERE Score >
(
    SELECT AVG(Score)
    FROM Customers
)
ORDER BY Score DESC;

-----------------------------------------------------------
-- Q3. Find the customer with the highest score.
-----------------------------------------------------------
SELECT
    ID,
    First_Name,
    Country,
    Score
FROM Customers
WHERE Score =
(
    SELECT MAX(Score)
    FROM Customers
);

-----------------------------------------------------------
-- Q4. Find customers who have never placed an order.
-----------------------------------------------------------
SELECT
    ID,
    First_Name,
    Country,
    Score
FROM Customers
WHERE ID NOT IN
(
    SELECT Customer_ID
    FROM Orders
);

-----------------------------------------------------------
-- Q5. Find the highest total sales generated by a customer.
-----------------------------------------------------------
SELECT
    MAX(TotalSales) AS Highest_Total_Sales
FROM
(
    SELECT
        Customer_ID,
        SUM(Sales) AS TotalSales
    FROM Orders
    GROUP BY Customer_ID
) AS SalesTable;

-----------------------------------------------------------
-- Q6. Find the highest single order value
-- for each customer.
-----------------------------------------------------------
SELECT
    ID,
    First_Name,
    MAX(Sales) AS Highest_Sales
FROM Customers
LEFT JOIN Orders
    ON Customer_ID = ID
GROUP BY
    ID,
    First_Name
HAVING MAX(Sales) IS NOT NULL
ORDER BY Highest_Sales DESC;

-----------------------------------------------------------
-- Find Second highest Salary
-----------------------------------------------------------
Select
    Max(Salary) SecondHIghestSalary
from Employee
where salary<(Select
Max(Salary)
from Employee)

---------------------------------------------------------------------------------------------------------------
/*Write a solution to report the first name, last name, city, and state of each person in the Person table. 
If the address of a personId is not present in the Address table, report null instead.*/
---------------------------------------------------------------------------------------------------------------
Select 
    p.firstName,
    p.lastName,
    case when city is null then null
    else city
    end City,
    case when state is null then null

-- Highest salary in each department
Select 
    Department,
    Employee,
    Salary
from (
Select 
    d.name as Department,
    e.name as Employee,
    e.Salary,
    Rank() over (Partition by departmentID Order by Salary Desc) as SalaryRank
from employee e
left join department d
on e.departmentid = d.id)t
where salaryrank = 1

-- Customers who never ordered
Select 
    c.name as Customers
from customers c
left join orders o
on c.id = o.customerid
where o.customerID is null

-- duplicate emails
Select distinct
email 
from(
Select 
    email,
    count(*) over (partition by email) as TotalCount
from person)t
where TotalCount>1

-- Top 3 highest salaries of each department
SELECT
    Department,
    Employee,
    Salary
FROM
(
    SELECT
        d.Name AS Department,
        e.Name AS Employee,
        e.Salary,
        dense_RANK() OVER
        (
            PARTITION BY DepartmentId
            ORDER BY Salary DESC
        ) AS SalaryRank
    FROM Employee AS e
    LEFT JOIN Department AS d
        ON d.Id = e.DepartmentId
) AS T
WHERE SalaryRank <=3;


---First Login
Select
    player_id,
    min(event_date) as first_login
from activity
group by player_id

--Rising Temperature 
Select 
  id 
from 
(
    Select 
    id,
    recordDate,
    temperature,
    lag(temperature) over (order by recorddate) prevtemp
    from weather
)t
where temperature>prevtemp

-- Duplicate emails
DELETE FROM Person
WHERE Id NOT IN
(
    SELECT MIN(Id)
    FROM Person
    GROUP BY Email
);

-- Select employee who has atleast five reports
Select 
name
from employee
where id in (
SELECT
    ManagerId
FROM Employee
GROUP BY ManagerId
having COUNT(*)>=5);
